name: build docs
on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
  pull_request:
    branches: [main]
    paths:
      - 'docs/**'
jobs:
  build_typst_documents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: typst-community/setup-typst@v5
        with:
          typst-version: 0.15.0
      - name: "Typst: paper"
        working-directory: "./docs/moretti-wojnarowski-2026"
        run: make
      - name: "Typst: presentation"
        working-directory: "./docs/internship-presentation"
        run: make
